spring:
  datasource:
    username: root
    password: 12345678
    url: jdbc:mysql://192.168.1.3:3306/blog?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT   #192.168.1.3 is my computer ip ,jpa is database name
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5Dialect
    generate-ddl: true

logging:
  level:
    root: warn
    com.springbootblog: info
  file:
    name: log/loigback.log
server:
  port: 8080